// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAQPGUw-Qf96qlgIND4WzUAu0CeYL03po',
    appId: '1:72076029788:web:51262920179ae93ba19b99',
    messagingSenderId: '72076029788',
    projectId: 'jk-product-f5be8',
    authDomain: 'jk-product-f5be8.firebaseapp.com',
    storageBucket: 'jk-product-f5be8.firebasestorage.app',
    measurementId: 'G-4D13PFR413',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1AWr_2sdJ5IN6PBPjD7bLxZcHy41fb9I',
    appId: '1:72076029788:android:f430173f5ab0050ca19b99',
    messagingSenderId: '72076029788',
    projectId: 'jk-product-f5be8',
    storageBucket: 'jk-product-f5be8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn8CtBTOMmRG0Nirw9c24kfGC3jQ85CyQ',
    appId: '1:72076029788:ios:4ac41459bc687b79a19b99',
    messagingSenderId: '72076029788',
    projectId: 'jk-product-f5be8',
    storageBucket: 'jk-product-f5be8.firebasestorage.app',
    iosBundleId: 'com.example.jkproduct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn8CtBTOMmRG0Nirw9c24kfGC3jQ85CyQ',
    appId: '1:72076029788:ios:4ac41459bc687b79a19b99',
    messagingSenderId: '72076029788',
    projectId: 'jk-product-f5be8',
    storageBucket: 'jk-product-f5be8.firebasestorage.app',
    iosBundleId: 'com.example.jkproduct',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAQPGUw-Qf96qlgIND4WzUAu0CeYL03po',
    appId: '1:72076029788:web:7cf02aff953b25f9a19b99',
    messagingSenderId: '72076029788',
    projectId: 'jk-product-f5be8',
    authDomain: 'jk-product-f5be8.firebaseapp.com',
    storageBucket: 'jk-product-f5be8.firebasestorage.app',
    measurementId: 'G-FFC1SW3VYS',
  );
}
